alter table "public"."profiles" drop constraint "profiles_pkey";

drop index if exists "public"."profiles_pkey";

create table "public"."player_profiles" (
    "player_id" bigint generated by default as identity not null,
    "profile_id" bigint not null
);


alter table "public"."player_profiles" enable row level security;

alter table "public"."profiles" drop column "profile_id";

alter table "public"."profiles" add column "id" bigint generated by default as identity not null;

CREATE UNIQUE INDEX player_profiles_pkey ON public.player_profiles USING btree (player_id, profile_id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

alter table "public"."player_profiles" add constraint "player_profiles_pkey" PRIMARY KEY using index "player_profiles_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."player_profiles" add constraint "public_player_profiles_player_id_fkey" FOREIGN KEY (player_id) REFERENCES players(id) not valid;

alter table "public"."player_profiles" validate constraint "public_player_profiles_player_id_fkey";

alter table "public"."player_profiles" add constraint "public_player_profiles_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) not valid;

alter table "public"."player_profiles" validate constraint "public_player_profiles_profile_id_fkey";

grant delete on table "public"."player_profiles" to "anon";

grant insert on table "public"."player_profiles" to "anon";

grant references on table "public"."player_profiles" to "anon";

grant select on table "public"."player_profiles" to "anon";

grant trigger on table "public"."player_profiles" to "anon";

grant truncate on table "public"."player_profiles" to "anon";

grant update on table "public"."player_profiles" to "anon";

grant delete on table "public"."player_profiles" to "authenticated";

grant insert on table "public"."player_profiles" to "authenticated";

grant references on table "public"."player_profiles" to "authenticated";

grant select on table "public"."player_profiles" to "authenticated";

grant trigger on table "public"."player_profiles" to "authenticated";

grant truncate on table "public"."player_profiles" to "authenticated";

grant update on table "public"."player_profiles" to "authenticated";

grant delete on table "public"."player_profiles" to "service_role";

grant insert on table "public"."player_profiles" to "service_role";

grant references on table "public"."player_profiles" to "service_role";

grant select on table "public"."player_profiles" to "service_role";

grant trigger on table "public"."player_profiles" to "service_role";

grant truncate on table "public"."player_profiles" to "service_role";

grant update on table "public"."player_profiles" to "service_role";


